name: PlayerProfiles
version: 7.0.0
main: com.muhammaddaffa.playerprofiles.PlayerProfiles
author: aglerr
description: Plugin to show player profiles
api-version: 1.13
softdepend: [CombatLogX, DeluxeCombat, PlaceholderAPI, WorldGuard, WorldEdit]

commands:
  playerprofiles:
    aliases: []
  profile:
    aliases: []
  unlockProfile:
    aliases: []
  lockProfile:
    aliases: []
  toggleprofile:
    aliases: []